### ISSUE TITLE
vue-hot-reload-api module

### ISSUE THREAD

**Issue by jackel27** [leMaur/phonegap-vueify#1]
First off, thank you for making this! I am not sure if this issue is from my end, but when I run ``` npm run dev``` I get the following errors: 
```
Error: Cannot find module 'vueify/node_modules/vue-hot-reload-api' from '...\testing\www\src'
```
and
```
Error: Cannot find module 'vueify/node_modules/vue-hot-reload-api' from '...\testing\www\src\components'
```
Tried updating modules, nodejs, and installing via all options to no avail. Thank you!

**Comment by brahbassim** [comment]
Did you do "npm install" to install all depenbdencies?

**Comment by leMaur** [comment]
...and also check if you have the latest version installed. Currently is the 1.0.7
