### ISSUE TITLE
More instructions?

### ISSUE THREAD

**Issue by glittle** [leMaur/phonegap-vueify#12]
Is there a source of documentation about how to use this template? It looks very good, but I'm sure there are many tricks and features that are documented somewhere. 

For example, the template has "hello.vue".  I can add a "page1.vue" file next to it, but how do I add that into the app and navigate between these two pages?

Some that seem to be related:
- https://github.com/vuejs-templates/browserify
- https://github.com/vuejs/vueify

Are there other major sources of documentation?

Thanks!

**Comment by OmgImAlexis** [comment]
You're asking how vuejs works, this has nothing todo with this template.
