### ISSUE TITLE
Build missing dependencies

### ISSUE THREAD

**Issue by Krisseck** [leMaur/phonegap-vueify#2]
`npm run dev` works okay, but `npm run build` gave me errors. I needed to manually install the following modules for it to work:
- shelljs
- adm-zip
- q

**Comment by leMaur** [comment]
Hi @Krisseck,

If you run `npm run build` without specify the platform, the _browser_ platform is used as a default.

I have updated the package.json, download it and after run again `npm install`.

Select the platform you desire to use, _ios_ or _android_ or both.
`npm run prepare ios` to select iOS platform.
`npm run prepare android` to select Android platform.

For debug on device: 
plug-in your device through usb and type `npm run ios` for iOS platform.
`npm run android` for Android platform.

For build your app:
`npm run build ios` or `npm run build android`.


I hope this helps you.
