### ISSUE TITLE
npm-run-all --parallel watchify serve

### ISSUE THREAD

**Issue by alexlauzon** [leMaur/phonegap-vueify#4]
I'm getting pretty often this error:
npm ERR! Failed at the phonegap-vueify@1.0.7 dev script 'npm-run-all --parallel watchify serve'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the phonegap-vueify package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm-run-all --parallel watchify serve

I use node v6.3.0 (npm v3.10.3)

Not sure if you can help or not. Node recommends that I tell you:
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm-run-all --parallel watchify serve

:-)

**Comment by YobertyAlej** [comment]
I've been having the same trouble with watchify.
Either way, it seems to be (at least for me) a node - watchify problem instead of a phonegap-vueify one.

**Comment by alexlauzon** [comment]
Thanks for the info!
