### ISSUE TITLE
run dev / hot-reload refreshes 2 times

### ISSUE THREAD

**Issue by blomdahldaniel** [leMaur/phonegap-vueify#5]
Hi!

This is a very cool project! I love it so far!

But I think there is something wrong (likely I got it wrong..) with the hot-reload. 

If i change, for example, the Hello.vue `<style>` stuff, for example the `color-bg`, first i see the update and then, 1 second later the server sort of refreshes itself. Then i see the loading-screen again and then the app opens up.. 

So sort of double work i feel..

Do you know what can be wrong?

**Comment by leMaur** [comment]
Hi @blomdahldaniel,

sorry but I do not have this problem. You can check the watchify instruction on https://github.com/substack/watchify.

**Comment by blomdahldaniel** [comment]
Okey, thank you!
