### ISSUE TITLE
Is it possible to have a webpack version of this template please?

### ISSUE THREAD

**Issue by RashadSaleh** [leMaur/phonegap-vueify#6]
Title says it all. Thanks for your work!

**Comment by leMaur** [comment]
Hi @RashadSaleh,
Thanks for appreciate my project.
I'm not a fan of webpack for this reason I chose browserify instead.

Anyway, you can try to join together the [Hello World Phonegap template](https://github.com/phonegap/phonegap-template-hello-world) and the [Vue.js Webpack template](https://github.com/vuejs-templates/webpack) exactly as I did with my project. Maybe you will have to adjust some parameters in webpack.

Good luck and happy coding!
