### ISSUE TITLE
Asking about the vuex 

### ISSUE THREAD

**Issue by vip30** [leMaur/phonegap-vueify#9]
Hi I found your project on vuejs forum, it is pretty cool.
I am newbie of phonegap but rather experienced user in vuejs.
Is it the same of using the plugins (eg: vue i18n, vue router) in phonegap comparing to website version ?
Thanks!

**Comment by YobertyAlej** [comment]
Hi, **Yes you can**!

I've been using this project and you can use 100% all the plugins and libs available out there (In fact i'm using vue-router and vuex for a hybrid app).

Best of luck.

**Comment by leMaur** [comment]
Hi guys,
and thanks @YobertyAlej for the answer! It's like that!
